const constants = {
    INIT_PLAYERS: "INIT_PLAYERS",
    CHANGE_PLAYER: "CHANGE_PLAYER",
    SET_PLAYER_GAME: "SET_PLAYER_GAME",
    SET_CURRENT_PLAYER: "SET_CURRENT_PLAYER",
    RESTART_GAME: "RESTART_GAME",
    COMPUTE: "COMPUTE",
    SET_PLAYER: "SET_PLAYER",
    GET_PLAYER: "GET_PLAYER",
    GET_ALL_PLAYERS: "GET_ALL_PLAYERS",
    GET_GAME: "GET_GAME",
    GET_CURRENT_PLAYER: "GET_CURRENT_PLAYER",
    GET_TOTAL_MOVEMENTS: "GET_TOTAL_MOVEMENTS",
    INCREASE_MOVEMENT: "INCREASE_MOVEMENT",
    SAVE_MOVEMENT: "SAVE_MOVEMENT",
    END_GAME: "END_GAME",
    CHANGE_PLAYER_NAME: "CHANGE_PLAYER_NAME"
}

export default constants